export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_ERROR = "SET_ERROR";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";

export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const ORDER_LOADING_RESET = "ORDER_LOADING_RESET";

export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const AUTHENTICATED = "AUTHENTICATED";
export const AUTHENTICATION_REQUEST_INIT = "AUTHENTICATION_REQUEST_INIT";

export const LOGOUT = "LOGOUT";
export const LOGOUT_INIT = "LOGOUT_INIT";
export const CHECKTIMEOUT = "CHECKTIMEOUT";

export const GET_INITIAL_STATE = "GET_INITIAL_STATE";